# Крок 1 — збираємо проект
FROM mcr.microsoft.comdotnetsdk9.0 AS build
WORKDIR src

# Копіюємо всі csproj і відновлюємо залежності
COPY CurrencyRates.APICurrencyRates.API.csproj CurrencyRates.API
COPY CurrencyRates.ApplicationCurrencyRates.Application.csproj CurrencyRates.Application
COPY CurrencyRates.DomainCurrencyRates.Domain.csproj CurrencyRates.Domain
COPY CurrencyRates.InfrastructureCurrencyRates.Infrastructure.csproj CurrencyRates.Infrastructure

RUN dotnet restore CurrencyRates.APICurrencyRates.API.csproj

# Копіюємо весь код і публікуємо
COPY . .
RUN dotnet publish CurrencyRates.APICurrencyRates.API.csproj -c Release -o apppublish

# Крок 2 — фінальний образ (легший, без SDK)
FROM mcr.microsoft.comdotnetaspnet9.0 AS final
WORKDIR app
COPY --from=build apppublish .

EXPOSE 8080

ENTRYPOINT [dotnet, CurrencyRates.API.dll]